#!/bin/sh
# Reset
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"


NC='\e[0m'
if [ $UUID != 0 ]; then
        echo "${I_KO}    Start the Script as 'root' for it to work properly    ${I_KO}";
        exit 1;
else
    packageUpdate0=$(apt update && apt list --upgradable 2> /dev/null | grep -c upgradable)
    packageUpdate=$((( $packageUpdate0 * 1 ) - 1))
    echo -e "Upadate : \t\t ${packageUpdate} packages";
fi