#!/bin/bash
if [ ! -f ~/upgrade-system ]; then
    date > ~/upgrade-system
    echo 'Updating everything ... '
    /usr/bin/x-terminal-emulator -e 'sudo upgrade-system'
    sleep 6s
    echo 'Turning off ... '
    rm ~/upgrade-system
    sudo poweroff
fi
