#!/bin/sh
# Reset
UUID=$(id -u)
UUID=$(( UUID + 0 ))
I_OK="✔"
I_KO="✖️"
Color_Off='\033[0m'       # Text Reset
Red='\033[0;31m'          # Red
Blue='\033[0;34m'         # Blue
IRed='\033[0;91m'         # Red


NC='\e[0m'
if [ $UUID != 0 ]; then
	echo "${I_KO}\t${Red}Start the Script as ${Blue}root${Red} for it to work properly${Color_Off}\t${I_KO}";
	exit 1;
else
        sh /usr/bin/upgrade-system;
	echo "${IRed}${I_OK}\t Poweroff ... \t\t\t\t\t\t\t\t\t${I_OK}${Color_Off}";
        sleep 3s;
        systemctl poweroff;
fi